server:
  port: 9985
  #[测试用]session会话过期时间：分钟
  servlet:
    session:
      timeout: 1
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
#    ?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 
  redis:
    host: localhost
    port: 6379
#    password: root

mybatis:
  mapper-locations: classpath:com/boot/mapper/*.xml
  type-aliases-package: com.boot.domain
#      logging.level.com.baizhi=debug
